file_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
# Rscript may encode spaces as ~+~ in its --file argument.
script_path <- gsub("~+~", " ", sub("^--file=", "", file_arg[[1]]), fixed = TRUE)
script_dir <- dirname(normalizePath(script_path, mustWork = TRUE))
project_root <- normalizePath(file.path(script_dir, ".."))
figures <- c("6", "7", "S8", "S9")
source(file.path(script_dir, "lib", "case_study_figures.R"))
figures <- c("S10", "S11")
source(file.path(script_dir, "lib", "quantile_figures.R"))
source(file.path(script_dir, "recreate_figure_S12.R"))
writeLines(capture.output(sessionInfo()), file.path(Sys.getenv("TWO_SAMPLE_FIGURE_DIR", file.path(project_root, "output", "case_study")), "sessionInfo.txt"))
